import AuthContext from './Pagecontext'
import Navbar from './components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthContext>
    <html lang="en bg-gray-100 ">
      <body className={inter.className}>
        <Navbar/>
        {children}
        </body>
    </html>
    </AuthContext>
  )
}
